### ISSUE TITLE
Cannot properly precompile Gurobi.

### ISSUE THREAD

**Issue by zxjroger** [JuliaOpt/Gurobi.jl#306] opened 2020-04-04 23:41 UTC
Hi, I am using Gurobi 9.0.1 in Julia 1.4.0. It worked fine until I update all packages. Then, by the following code
```
using Distributed
addprocs(Sys.CPU_THREADS-1)
@everywhere using Gurobi
```
I got the following warning on each worker I added.
```
[ Info: Precompiling Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b]
┌ Warning: Module MathOptInterface with build ID 582350528813909 is missing from the cache.
│ This may mean MathOptInterface [b8f27783-ece8-5eb3-8dc8-9495eed66fee] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1016
```
I tried to remove Gurobi and MathOptInterface and reinstall them, but the warning is still there. Also, sometimes I got this warning when I use other packages
```
┌ Warning: Replacing module `MathOptInterface`
└ @ Base loading.jl:947
```
Any suggestions would be appreciated.

**Comment by zxjroger** [comment] 2020-04-05 00:46
Also, after I set
```
ENV["GUROBI_HOME"]  = "/Library/gurobi901/mac64"
```
in Julia. Each time I restart Julia, I will need to do it again. I believe Julia would remember it once I set it previously.

**Comment by odow** [comment] 2020-04-05 00:54
1. You only been to set `"GUROBI_HOME"` environment variable when you build Gurobi. Julia will not remember it between sessions. (You can permanently set it, see, e.g., https://apple.stackexchange.com/questions/106778/how-do-i-set-environment-variables-on-os-x).

2. The issue is that precompilation doesn't play nice with `Distributed`. In this case, each proc checks if it has been precompiled, decides no, and then they all try to precompile over each other and get confused. To fix, start Julia with one thread. Precompile via `using Gurobi`. Exit Julia. Then restart and load your procs.

**Comment by zxjroger** [comment] 2020-04-05 02:30
Thanks for your response. I tried what you wrote in the second paragraph, but I still got the same warning. Also, each time I start Julia with one thread, and `using Gurobi`, it will precompile:
```
[ Info: Precompiling Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b]
```
If I start Julia and using a different package first say `using JuMP`, then `using Gurobi`, I got the following warning:
```
[ Info: Precompiling Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b]
┌ Warning: Module MathOptInterface with build ID 582350528813909 is missing from the cache.
│ This may mean MathOptInterface [b8f27783-ece8-5eb3-8dc8-9495eed66fee] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1016
[ Info: Skipping precompilation since __precompile__(false). Importing Gurobi [2e9cd046-0924-5485-92f1-d5272153d98b].
```
Could it be something wrong with the `MathOptInterface` package?

**Comment by odow** [comment] 2020-04-05 02:36
Try deleting `~/.Julia/compiled`. Some things might have got out of whack.

Do you have persistent write access to `~/.Julia/compiled`? Once Gurobi is precompiled (e.g., on your single thread), closing Julia and re-opening should not trigger the need to precompiled, regardless of other packages.

The `__precompile__(false)` statement is _very_ weird. Are you on the latest versions? (What's the output of `] st`?

**Comment by zxjroger** [comment] 2020-04-05 03:12
Thank you very much. After I deleted file "compiled" and re-compile everything. No warnings anymore.

It was indeed very weird. There was no problem with any other packages and they do not need to precompile each time I start Julia. I guess I triggered something, then Julia stopped reading precompile document for Gurobi in the file compile.

**Comment by zxjroger** [comment] 2020-04-05 03:53
For anyone interested in setting `GUROBI_HOME` permanently on Mac with zsh terminal. This is what you should do,

1. Check if you have a file `.zprofile` at `/Users/username`, if not, then you need to create a text file under this name.
2. Add the following line to `.zprofile` and save:
`export GUROBI_HOME=/Library/gurobi901/mac64`
Note that you should change the version number accordingly.
Then, in your zsh terminal, type `source ~/.zprofile` to execute it.
Then, in both of your zsh terminal and Julia, type `ENV`, you should find `GUROBI_HOME` directory there.

**Comment by odow** [comment] 2020-04-05 04:03
Glad you got it working.

**Closed by odow** 2020-04-05 04:03 UTC
