### ISSUE TITLE
Confirmed upstream bug: get/set of objective coefficients

### ISSUE THREAD

**Issue by odow** [JuliaOpt/Gurobi.jl#60] opened 2016-09-15 22:23 UTC
See https://groups.google.com/forum/#!topic/gurobi/R9SuKdb8YHc for the discussion.

Files demonstrating this (in both Julia and Python) are here
https://gist.github.com/odow/5255c34daef85a752da76b3836f20be3

Briefly:

After solving some LP, we add a new constraint
https://gist.github.com/odow/5255c34daef85a752da76b3836f20be3#file-main-jl-L25-L26

During the subsequent resolve (https://gist.github.com/odow/5255c34daef85a752da76b3836f20be3#file-main-jl-L30), Gurobi reformulates the model

The LP (and MPS) file of the model at this stage leaks this reformulation (minor bug).
https://gist.github.com/odow/5255c34daef85a752da76b3836f20be3#file-3_julia-jl-L1-L16

However, this leak does not occur through the other API's. Therefore, when we get the objective coefficients, we query the original coefficients. 
https://gist.github.com/odow/5255c34daef85a752da76b3836f20be3#file-main-jl-L34

When we set the objective coefficients (which on resolve, JuMP always does using the original JuMP model coefficients https://github.com/JuliaOpt/JuMP.jl/blob/master/src/solvers.jl#L356 ), we trigger a bug, overriding the reformulated coefficients with this original coefficients.
https://gist.github.com/odow/5255c34daef85a752da76b3836f20be3#file-main-jl-L35

In the next solve, Gurobi "undoes" the formulation, but doesn't account for us resetting the correct (but incorrect for that formulation) coefficients (major bug).

This creates the unboundedness.
https://gist.github.com/odow/5255c34daef85a752da76b3836f20be3#file-julia-log-L39

This is pretty worrying for any model solved with JuMP and Gurobi as JuMP always performs this supposed no-op of getting and setting the objective coefficients. If Gurobi has ever reformulated a model in a way that is not unbounded, there would be no way of knowing (short of manually recalculating the objective) that the objective coefficients were switched, leading to an incorrect solution.

@mlubin

**Comment by mlubin** [comment] 2016-09-24 23:47
Closing since gurobi confirmed it's an upstream issue

**Closed by mlubin** 2016-09-24 23:47 UTC

**Comment by mlubin** [comment] 2016-09-24 23:50
@odow, I'm open to suggestions on how to avoid incorrect solutions until the next gurobi release. Do you have any understanding of the potential scope of this issue?

**Comment by odow** [comment] 2016-09-25 00:03
I just tested the Beta version for Gurobi 7.0 which fixes this.

Try running https://gist.github.com/odow/436a33e76297d1294e02d48898ca9b27

<b>Gurobi will report Optimal. But the objective, solution vector and dual variables are all incorrect.<b>

From my correspondence with Gurobi, the bug is triggered with a variable that is finitely bounded above, not bounded below and Gurobi chooses not to rescale the problem.

We think it has something to do with (nearly) colinear constraints, but we have no idea about how widespread this issue is.

Although this seems like a very obscure corner case, I have run into this multiple times with "real world" models.

Still waiting for a response on what version it was introduced.

**Comment by odow** [comment] 2016-09-25 00:06
I guess we could store the objective vector from MPB and verify that `c'x` is the the reported objective.

**Comment by daschw** [comment] 2016-11-03 09:56
I ran into this error message with both, Gurobi 6.5 and Gurobi 7.0:
```
    You have encountered a known bug in Gurobi. Any information you query from the model may be incorrect.
    This bug has existed since the first version of Gurobi but is fixed in Gurobi v7.0.

    For more information go to https://github.com/JuliaOpt/Gurobi.jl/issues/60.
    Please leave a comment stating that you encountered this bug! We would like to know how prevalent it is.

 in updatemodel!(::Gurobi.GurobiMathProgModel) at C:\Users\schwabeneder\.julia\v0.5\Gurobi\src\GurobiSolverInterface.jl:215
 in setvartype!(::Gurobi.GurobiMathProgModel, ::Array{Symbol,1}) at C:\Users\schwabeneder\.julia\v0.5\Gurobi\src\GurobiSolverInterface.jl:388
 in #build#93(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at C:\Users\schwabeneder\.julia\v0.5\JuMP\src\solvers.jl:404
 in (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at .\<missing>:0
 in #solve#88(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at C:\Users\schwabeneder\.julia\v0.5\JuMP\s...
```
Replacing two-sided (range) constraints with two seperate constraints fixed this issue for me. I don't know how this is related to the above error message, but fortunately this warning
```
WARNING: Julia Gurobi interface doesn't properly support range (two-sided) constraints. See Gurobi.jl issue #14
```
gave me the right hint.

**Comment by odow** [comment] 2016-11-03 18:36
Hi @daschw thanks for reporting this. That error message shouldn't be triggered here. You are correct  that the range constraints are the real issue.

**Comment by dourouc05** [comment] 2017-02-09 15:15
I've just come accross this error message when running my code. More precisely, this is what I got: 

```
ERROR: LoadError:     You have encountered a known bug in Gurobi. Any information you query from the model may be incorrect.
    This bug has existed since the first version of Gurobi but is fixed in Gurobi v7.0.

    For more information go to https://github.com/JuliaOpt/Gurobi.jl/issues/60.
    Please leave a comment stating that you encountered this bug! We would like to know how prevalent it is.

 in updatemodel! at C:\Users\Thibaut\.julia\v0.4\Gurobi\src\GurobiSolverInterface.jl:218
 in setvartype! at C:\Users\Thibaut\.julia\v0.4\Gurobi\src\GurobiSolverInterface.jl:391
 in build at C:\Users\Thibaut\.julia\v0.4\JuMP\src\solvers.jl:404
 in solve at C:\Users\Thibaut\.julia\v0.4\JuMP\src\solvers.jl:134
 in productionModel at F:\Univ\_PhD\Industore\Hg\WeeklyPlanning\test\../src\model\production.jl:23
 in modelMultiple at F:\Univ\_PhD\Industore\Hg\WeeklyPlanning\test\../src\model\hr.jl:180
 [inlined code] from F:\Univ\_PhD\Industore\Hg\WeeklyPlanning\test\tests_is.jl:111
 in anonymous at no file:0
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
while loading F:\Univ\_PhD\Industore\Hg\WeeklyPlanning\test\tests_is.jl, in expression starting on line 42
```

The problem is, I've updated Gurobi to version 7.0.2 (and it is the only version installed on my computer --- or some software installs a version without my knowing). This is unlikely a problem in my code (it happened after 330 experiments, each of which running roughly 50 times two optimisation models, with slight variations in the parameters of the model). 

I run Julia 0.4.6 (migrating all my code to 0.5 would take a lot of time, which I don't currently have…), with these versions (Gurobi.jl 0.2.8, i.e. the latest version): 

```
31 required packages:
 - AmplNLWriter                  0.2.3
 - ArrayFire                     0.0.4
 - ArrayViews                    0.6.4
 - Atom                          0.4.6
 - CPLEX                         0.1.7
 - CoinOptServices               0.1.2
 - Convex                        0.4.0
 - DReal                         0.1.0
 - DataFrames                    0.8.5
 - Distributions                 0.11.1
 - Documenter                    0.8.10
 - Escher                        0.3.3+             master
 - GR                            0.19.0
 - Gurobi                        0.2.8
 - HypothesisTests               0.4.0
 - IJulia                        1.4.1
 - Ipopt                         0.2.6
 - JSON                          0.8.2
 - JuMP                          0.14.1             c89327dc (dirty)
 - Lint                          0.2.5
 - Mosek                         0.4.0
 - Optim                         0.6.1
 - Plots                         0.8.2
 - ProgressMeter                 0.3.3
 - PyPlot                        2.2.4
 - RDatasets                     0.2.0
 - SCS                           0.2.7
 - SIUnits                       0.1.0
 - StatPlots                     0.0.3
 - TimeSeries                    0.8.8
 - UnicodePlots                  0.1.4
86 additional packages:
 - AbstractDomains               0.1.0
 - ArgParse                      0.4.0
 - AxisAlgorithms                0.1.5
 - Benchmark                     0.1.0
 - BinDeps                       0.4.5
 - Blink                         0.3.5
 - BufferedStreams               0.2.3
 - Calculus                      0.2.0
 - Cbc                           0.2.5
 - Clp                           0.2.2
 - CodeTools                     0.3.1
 - Codecs                        0.2.0
 - ColorTypes                    0.2.12
 - Colors                        0.6.9
 - Combinatorics                 0.2.1
 - Compat                        0.14.0
 - Conda                         0.4.0
 - DataArrays                    0.3.11
 - DataStructures                0.5.2
 - DataTransformations           0.0.0-             master (unregistered)
 - Dates                         0.4.4
 - DocStringExtensions           0.3.1
 - ExtremeValueDistributions     0.0.0-             develop (unregistered)
 - FactCheck                     0.4.3
 - FileIO                        0.2.2
 - FixedPointNumbers             0.2.1
 - FixedSizeArrays               0.2.5
 - ForwardDiff                   0.2.5
 - FunctionalCollections         0.2.0
 - GZip                          0.2.20
 - Hiccup                        0.0.3
 - HttpCommon                    0.2.6
 - HttpParser                    0.2.0
 - HttpServer                    0.1.7
 - Interpolations                0.3.6
 - Iterators                     0.2.0
 - JuliaParser                   0.6.4
 - Juno                          0.2.5
 - KernelDensity                 0.3.0
 - LNR                           0.0.2
 - LaTeXStrings                  0.2.0
 - Lazy                          0.11.5
 - LibExpat                      0.2.4
 - Libz                          0.2.2
 - LightXML                      0.4.0
 - MacroTools                    0.3.4
 - Markdown                      0.3.0
 - MathProgBase                  0.5.10
 - MbedTLS                       0.3.0
 - Measures                      0.0.3
 - Media                         0.2.5
 - MetropolisUpdaters            0.0.0-             master (unregistered)
 - Mustache                      0.1.3
 - Mux                           0.2.3
 - NaNMath                       0.2.2
 - Nettle                        0.2.4
 - PDMats                        0.5.4
 - Patchwork                     0.3.0
 - PlotUtils                     0.0.4
 - PolynomialFactors             0.0.3
 - Polynomials                   0.1.2
 - PositiveFactorizations        0.0.4
 - Primes                        0.1.2
 - PyCall                        1.7.1              0c8e5165 (dirty)
 - RData                         0.0.4
 - Ratios                        0.0.4
 - Reactive                      0.3.6
 - RecipesBase                   0.0.6
 - Reexport                      0.0.3
 - Requires                      0.2.3
 - ReservoirManagement           0.0.0-             master (unregistered, dirty)
 - ReverseDiffSparse             0.5.8
 - Rmath                         0.1.6
 - Roots                         0.3.0
 - SHA                           0.3.0
 - Showoff                       0.0.7
 - SortingAlgorithms             0.1.0
 - StatsBase                     0.12.0
 - StatsFuns                     0.4.0
 - TexExtensions                 0.0.3
 - TextWrap                      0.1.6
 - URIParser                     0.1.7
 - WebSockets                    0.2.1
 - WinRPM                        0.2.3
 - WoodburyMatrices              0.2.1
 - ZMQ                           0.4.1
```

**Comment by odow** [comment] 2017-02-13 01:32
Are you able to share any of the code?

Do you have a repeatable example?

You can comment out [these lines](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/GurobiSolverInterface.jl#L222-L230) but I would advise that you manually check the solution is what you expect.

**Comment by mburq** [comment] 2017-03-21 14:48
I've also run across this error message: 

    ERROR: LoadError:     You have encountered a known bug in Gurobi. Any information you query from the model may be incorrect.
    This bug has existed since the first version of Gurobi but is fixed in Gurobi v7.0.

    For more information go to https://github.com/JuliaOpt/Gurobi.jl/issues/60.
    Please leave a comment stating that you encountered this bug! We would like to know how prevalent it is.

    in updatemodel!(::Gurobi.GurobiMathProgModel) at /Users/mburq/.julia/v0.5/Gurobi/src/GurobiSolverInterface.jl:218
    in setvartype!(::Gurobi.GurobiMathProgModel, ::Array{Symbol,1}) at /Users/mburq/.julia/v0.5/Gurobi/src/GurobiSolverInterface.jl:391
    in #build#102(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at /Users/mburq/.julia/v0.5/JuMP/src/solvers.jl:406
    in (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at ./<missing>:0
    in #solve#97(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /Users/mburq/.julia/v0.5/JuMP/src/solvers.jl:135

I've updated Gurobi to version 7.0.2 and I am running Julia 0.5.0 and Gurobi.jl 0.3.0.
I am solving a matching MIP with JuMP repeatedly (the bug appears around 500-600th solve). 

    function lp(w::Array{Float64}, g::LightGraphs.DiGraph)
        m = init_model(p)
        n = pool.n
        @variable(m, 1 >= y[1:n] >= 0, Int)
        @variable(m, 1 >= x[collect(edges(g))] >= 0, Int)

        @objective(m, Max, sum(y[j] * (1 - w[j]) for j in 1:n))
        @constraint(m, c2[k=1:n], sum(x[Pair(i,k)] for i=badj(g)[k]) == y[k])
        @constraint(m, c1[k=1:n], sum(x[Pair(k,j)] for j=fadj(g)[k]) == y[k])
        @constraint(m, c4[i=1:n, j=intersect(fadj(g)[i], badj(g)[i])],
              x[Pair(i,j)] == x[Pair(j,i)])
        status = solve(m)
    end

I've tried to take the exact input that yields the error to get a repeatable error, but solving it on its own does not cause any problem. It seems to me that the bug is linked repeated nature of my original code.

**Comment by odow** [comment] 2017-03-21 19:10
Hi @mburq 

If this is the same problem, I can attest that bug hunting on the 500th solve is extremely difficult!

Do you have a fully self-contained script that I could run to test? You could post it as a gist (gist.github.com) or email to me privately (my email is on my github profile) if you would prefer not to publically share the code.

Otherwise you could comment out [these lines](https://github.com/JuliaOpt/Gurobi.jl/blob/6d9f03908de8851e08c553b82eee046308cae9b6/src/GurobiSolverInterface.jl#L246-L254) to avoid throwing the error. Although I wouldn't vouch for the correctness of the solution.

**Comment by mburq** [comment] 2017-03-22 23:32
It seems that the bug was caused by some kind of overflow in floating point operations when parameters in the objective that are unusually large. Here's a repeatable error:
 
    using JuMP
    using Gurobi

    function bug(w)
      m = Model(solver=GurobiSolver(OutputFlag = 0))
      @variable(m, y >= 0, Int)
      @objective(m, Min, y * w)
      status = solve(m)
    end

Running `bug(1e100)` or `bug(1.2e99)` are both fine, but `bug(1.2e100)` returns the error message.

For me this fixed the problem given that the parameters were not supposed to be that large in the first place.

**Comment by davidov77** [comment] 2017-03-31 03:14
I got an error using GurobiSolver when loading and solving a .lp file (and as suggested I´m just leaving a comment here)

`m=MathProgBase.LinearQuadraticModel(GurobiSolver())
MathProgBase.loadproblem!(m, filename)
MathProgBase.optimize!(m)`

**Comment by odow** [comment] 2017-03-31 05:47
This is fixed but it wasn't tagged. Just wait for https://github.com/JuliaLang/METADATA.jl/pull/8619 to be merged.

**Comment by rdeits** [comment] 2017-04-12 17:13
I'm seeing this same issue with a very simple model, even with Gurobi.jl v0.3.1 and Gurobi v7.0.1. To reproduce:

```julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.1 (2017-03-05 13:25 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using JuMP, Gurobi

julia> Gurobi.version
v"7.0.1"

julia> Pkg.installed("Gurobi")
v"0.3.1"

julia> m = Model(solver=GurobiSolver())
Feasibility problem with:
 * 0 linear constraints
 * 0 variables
Solver is Gurobi

julia> @variable m x
x

julia> @constraint m x >= 1.0
x ≥ 1

julia> @constraint m x <= 0.5
x ≤ 0.5

julia> JuMP.build(m)

julia> MathProgBase.addvar!(internalmodel(m), [1, 2], [1.0, -1.0], -Inf, Inf, 0)

julia> solve(m)
ERROR:     You have encountered a known bug in Gurobi. Any information you query from the model may be incorrect.
    This bug has existed since the first version of Gurobi but is fixed in Gurobi v7.0.

    For more information go to https://github.com/JuliaOpt/Gurobi.jl/issues/60.
    Please leave a comment stating that you encountered this bug! We would like to know how prevalent it is.

 in updatemodel!(::Gurobi.GurobiMathProgModel) at /home/rdeits/.julia/v0.5/Gurobi/src/GurobiSolverInterface.jl:247
 in setvartype!(::Gurobi.GurobiMathProgModel, ::Array{Symbol,1}) at /home/rdeits/.julia/v0.5/Gurobi/src/GurobiSolverInterface.jl:424
 in #build#114(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at /home/rdeits/.julia/v0.5/JuMP/src/solvers.jl:440
 in (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at ./<missing>:0
 in #solve#109(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /home/rdeits/.julia/v0.5/JuMP/src/solvers.jl:166
 in solve(::JuMP.Model) at /home/rdeits/.julia/v0.5/JuMP/src/solvers.jl:148
```

**Comment by mlubin** [comment] 2017-04-12 17:19
It seems like checking for this gurobi bug is causing more issues than it's preventing. Do we have any evidence that a bug exists in Gurobi v7.0 or later? Could we remove our checks and drop support for Gurobi pre-7.0?

**Comment by rdeits** [comment] 2017-04-12 18:03
My only piece of evidence is that just deleting the error message seemed to result in gurobi giving the right answer for my modified problem.

**Comment by joehuchette** [comment] 2017-04-12 18:07
What about changing the error to a warning?

**Comment by odow** [comment] 2017-04-12 20:56
Two points:
1. agree that this is causing more issues. I have no evidence that it exists v7.-, but we have found that Gurobi v6.5 is faster due to lower memory consumption so it's useful (for me) to retain this error. I could move it into my own code though...

2. @rdeits' example arises from the fact that a variable is introduced via MPB but not into JuMP. When JuMP, it updates the Gurobi model with it's representation of the objective vector, but the new objective vector `c` has less elements than specified by `num_vars(m.inner)` [here is the line](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/GurobiSolverInterface.jl#L204). It would seem Gurobi recognises that it is undefined and zeros it when it goes to solve.

Here is a gist https://gist.github.com/odow/2dd99948fde8ae8bafc92f3f40d6aa2e

**Comment by mlubin** [comment] 2017-04-12 21:01
Could we explicitly disable the error when the gurobi version is 7.0.0 or greater?
