### ISSUE TITLE
error compiling #GurobiMathProgModel#10: error compiling Type: could not load library "gurobi75"

### ISSUE THREAD

**Issue by steffiel** [JuliaOpt/Gurobi.jl#108] opened 2017-10-26 12:17 UTC
Hi all,

I tried to solve an IP with JuMP using Gurobi. Yet I get an error:

> julia> status=solve(m)
ERROR: error compiling #GurobiMathProgModel#10: error compiling Type: could not
load library "gurobi75"
The specified module could not be found.

>Stacktrace:
 [1] (::Core.#kw#Type)(::Array{Any,1}, ::Type{Gurobi.GurobiMathProgModel}, ::Voi
d) at .\<missing>:0
 [2] LinearQuadraticModel(::Gurobi.GurobiSolver) at C:\Users\Steffie\.julia\v0.6
\Gurobi\src\GurobiSolverInterface.jl:68
 [3] #build#119(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model)
at C:\Users\Steffie\.julia\v0.6\JuMP\src\solvers.jl:356
 [4] (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at .\<miss
ing>:0
 [5] #solve#116(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model
) at C:\Users\Steffie\.julia\v0.6\JuMP\src\solvers.jl:168
 [6] solve(::JuMP.Model) at C:\Users\Steffie\.julia\v0.6\JuMP\src\solvers.jl:150

>julia> ENV["GUROBI_HOME"]
"C:\\gurobi751\\win64"

My Gurobi version is 0.3.3 and in the following line is stated in the  /deps/build.jl file:
> aliases = ["gurobi75","gurobi70","gurobi65","gurobi60","gurobi56","gurobi55"]

Do you have any suggestions/ tips?

Thanks! 
Steffie

**Comment by odow** [comment] 2017-10-26 19:51
Did `Pkg.build("Gurobi")` work okay?

**Comment by steffiel** [comment] 2017-10-26 19:53
Yes I tried that, but it didn't work unfortunately.

**Comment by odow** [comment] 2017-10-26 19:56
What was the error from `Pkg.build`?

**Comment by steffiel** [comment] 2017-10-26 19:57
Oh I'm sorry, it worked without giving any error. However it did not solve the problem.

**Comment by odow** [comment] 2017-10-26 20:05
I just downloaded a 7.5.1 and cannot reproduce this.

In a fresh Julia REPL, what is the output of each of these lines?
```julia
julia> ENV["GUROBI_HOME"]
julia> using Gurobi
julia> Gurobi.version
```
What files are in the directory `C:/gurobi751/win64/bin`?

What is the contents of `C:/Users/Steffie.julia/v0.6/Gurobi/deps/deps.jl`?

**Comment by steffiel** [comment] 2017-10-27 08:38
I tried some other stuff this morning and it works. Although, I am not sure what solved it exactly.

Thanks for helping!!

**Comment by odow** [comment] 2018-03-22 20:54
Closing as this doesn't seem to be an issue with Gurobi.jl.

**Closed by odow** 2018-03-22 20:54 UTC
