### ISSUE TITLE
linear10b: Test Failed

### ISSUE THREAD

**Issue by schalil** [JuliaOpt/Gurobi.jl#223] opened 2019-07-11 21:07 UTC
I was testing Gurobi package (Gurobi v0.6.0) after installing gurobi 8.1.1. i am getting the below error.
`
(v1.1) pkg> test Gurobi
`

`
Linear10b: Test Failed at /Users/cms/.julia/packages/MathOptInterface/C3lip/src/Test/contlinear.jl:1250
  Expression: MOI.supports_constraint(model, MOI.ScalarAffineFunction{Float64}, MOI.Interval{Float64})
Stacktrace:
 [1] linear10btest(::Gurobi.Optimizer, ::MathOptInterface.Test.TestConfig) at /Users/cms/.julia/packages/MathOptInterface/C3lip/src/Test/contlinear.jl:1250
 [2] macro expansion at /Users/cms/.julia/packages/MathOptInterface/C3lip/src/Test/config.jl:53 [inlined]
 [3] macro expansion at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Test/src/Test.jl:1083 [inlined]
 [4] contlineartest(::Gurobi.Optimizer, ::MathOptInterface.Test.TestConfig, ::Array{String,1}) at /Users/cms/.julia/packages/MathOptInterface/C3lip/src/Test/config.jl:53
Academic license - for non-commercial use only
linear10b: Error During Test at /Users/cms/.julia/packages/MathOptInterface/C3lip/src/Test/config.jl:52
  Got exception outside of a @test
  MathOptInterface.UnsupportedConstraint{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.Interval{Float64}}: `MathOptInterface.ScalarAffineFunction{Float64}`-in-`MathOptInterface.Interval{Float64}` constraints is not supported by the model.
`

**Comment by odow** [comment] 2019-07-11 21:33
Thanks for the report. This is already fixed on the latest master. It just needs a release.

**Closed by odow** 2019-07-11 21:33 UTC

**Comment by odow** [comment] 2019-07-11 21:35
I should also add, it is not a bug with Gurobi.jl, so you're fine to continue using the package on v0.6.0. We now intentionally exclude the test.
