### ISSUE TITLE
Discrepancy between JuMP's getobjectivevalue and OBJ in Gurobi's Log

### ISSUE THREAD

**Issue by delft52** [JuliaOpt/Gurobi.jl#263] opened 2019-10-22 11:08 UTC
I have come across a strange mismatch between what JuMP and Gurobi report. I solve a MIP using an initial feasible solution that Gurobi confirms "Loaded MIP start with objective 93". However, getobjectivevalue(m) gives 63, and the best objective reached in the Gurobi log is 93. Using the solution values and calculating the objective by hand, the value given by JuMP (63) is correct and I can verify the feasible solution. Because of this discrepancy, I cannot use the MIP gap reported in Gurobi's log. Where can the discrepancy originate from? The complexity is that in Julia/JuMP it adds up and can be verified, but the Gurobi log values are off. There seems to be a fixed difference between them because when JuMP gives 62, in the Gurobi log it is 92.

**Comment by delft52** [comment] 2019-10-22 12:03
I think I have found the cause of the difference. In my objective function, there is a constant -30. JuMP includes that when calculating the objective value, but Gurobi discards it as it has no impact on the solution.

**Comment by odow** [comment] 2019-10-22 13:32
That looks like you're using an old version of JuMP. Upgrade to Julia 1.2 and the latest version of Gurobi.jl.

**Comment by delft52** [comment] 2019-10-22 15:20
> That looks like you're using an old version of JuMP. Upgrade to Julia 1.2 and the latest version of Gurobi.jl.

Thanks for the advice. My code is in Julia 0.6 since a couple of years ago and it will be a lot of rework to take it to 1.2. I only need to repeat some numerical experiments.

**Comment by odow** [comment] 2019-10-22 15:56
JuMP 0.18.x doesn't pass the constant in the objective to the solver. Instead it cached the solution inside JuMP.

Is JuMP reporting an incorrect solution? If so, that's a bug. If it is just the difference between JuMP and the written Gurobi log, that is intended behavior.

**Comment by delft52** [comment] 2019-10-22 16:16
> JuMP 0.18.x doesn't pass the constant in the objective to the solver. Instead it cached the solution inside JuMP.
> 
> Is JuMP reporting an incorrect solution? If so, that's a bug. If it is just the difference between JuMP and the written Gurobi log, that is intended behavior.

I'm indeed using JuMP 0.18x and it does not report an incorrect solution. Only the difference between getobjectivevalue() and the Gurobi log value was the issue.

**Comment by odow** [comment] 2019-10-22 20:57
Closing since this is intended behavior. Please re-open if you encounter any bugs, but note that Julia 0.6 (and JuMP 0.18.x to some extent) is now unsupported.

**Closed by odow** 2019-10-22 20:57 UTC
