### ISSUE TITLE
Why is Gurobi slower than JuMP+Gurobi?

### ISSUE THREAD

**Issue by zxjroger** [JuliaOpt/Gurobi.jl#279] opened 2019-12-09 22:01 UTC
I am trying to solve a linear programming problem. I added Gurobi.jl package and installed the software Gurobi 8.0.1. Because I need to solve this problem millions of times, so I am trying to find a way to make it as fast as I can. First, I tried to code in JuMP and call Gurobi as the solver. Second, I code purely in Julia and am only using Gurobi. However, I find that the second approach is much slower than the first approach, which is very counter-intuitive. I thought the second approach should be faster as it saves the time for JuMP to analyze the problem. I will really appreciate if anyone can give me some suggestions. I can add my code and problem if needed. Thank you very much.

**Comment by odow** [comment] 2019-12-09 22:22
JuMP + Gurobi should be fast because we try very hard to make it so. I routinely solve millions of parameterized linear programs using JuMP + Gurobi.

If you haven't already, you can use JuMP in "direct mode" via
```Julia
model = JuMP.direct_model(Gurobi.Optimizer())
@variable(model, x)
```
This should cut your memory usage in half, and should result in performance close to C.

One exception is deleting variables, which is currently `O(n^2)` in the number of variables to delete because of Gurobi's update semantics. We have some ideas for how to fix this though.

> I find that the second approach is much slower than the first approach, which is very counter-intuitive.

It's impossible to say without seeing your code. You should read https://docs.julialang.org/en/v1/manual/performance-tips/index.html.

In general, I would stay with JuMP + Gurobi.

**Comment by zxjroger** [comment] 2019-12-09 23:09
Thank you odow. 

I am trying to maximize scalar W_ub subject to some linear equalities and inequalities in the form of say \lambda_i^1+\lambda_j^2 >= constant.

This is the code for JuMP+Gurobi.

            model_ub = Model(with_optimizer(Gurobi.Optimizer, Presolve=0, OutputFlag=0))
            # model_ub = JuMP.direct_model(Gurobi.Optimizer(Presolve=0, OutputFlag=0))
            @variable(model_ub, W_ub)
            @variable(model_ub, lambda_1[1:N])
            @variable(model_ub, lambda_2[1:N])
            for i_ub = 1:N
                for j_ub = 1:N
                    if i_ub == i && j_ub == j
                        @constraint(model_ub, W_ub <= lambda_1[i_ub] + lambda_2[j_ub])
                    elseif H_star[i_ub,j_ub] == 1
                        @constraint(model_ub, W[i_ub,j_ub] == lambda_1[i_ub] + lambda_2[j_ub])
                    else H_star[i_ub,j_ub] == 0
                        @constraint(model_ub, W[i_ub,j_ub] <= lambda_1[i_ub] + lambda_2[j_ub])
                    end
                end
            end
            @objective(model_ub, Max, W_ub)
            optimize!(model_ub)
            if termination_status(model_ub) == MOI.OPTIMAL || termination_status(model_ub) == MOI.LOCALLY_SOLVED
                W_bound = value.(W_ub)
                println("W_upper_bound($i,$j)=$W_bound")
            else
                error("The model_ub was not solved correctly.")
            end

----

This is my code for Gurobi only:

            model_ub = Gurobi.Model(env, "model_ub", :maximize)
            # add variables
            # add_cvar!(model, obj_coef, lower_bound, upper_bound)
            add_cvars!(model_ub, zeros(2N),  -Inf, Inf)  # lambda_1 and lambda_2
            add_cvar!(model_ub, 1.0, -Inf, Inf)  # W_ub

            # For Gurobi, you have to call update_model to have the
            # lastest changes take effect
            update_model!(model_ub)

            # add constraints
            # summarize coefficients of constraints into a matrix
            matrix_ub = zeros(N^2, 2N+1)
            for i_ub = 1:N
                for j_ub = 1:N
                    matrix_ub[(i_ub-1)*N+j_ub, i_ub] = 1
                    matrix_ub[(i_ub-1)*N+j_ub, N+j_ub] = 1
                end
            end
            matrix_ub[(i-1)*N+j, 2N+1] = -1
            vector_ub = zeros(N^2)
            for i_ub = 1:N
                for j_ub = 1:N
                    vector_ub[(i_ub-1)*N+j_ub] = W[i_ub, j_ub]
                end
            end
            vector_ub[(i-1)*N+j] = 0

            # add_constr!(model, coefs, sense, rhs)
            for i_ub = 1:N
                for j_ub = 1:N
                    if H_star[i_ub, j_ub] == 1
                        add_constr!(model_ub, matrix_ub[(i_ub-1)*N+j_ub,:], '=', vector_ub[(i_ub-1)*N+j_ub])
                    else
                        add_constr!(model_ub, matrix_ub[(i_ub-1)*N+j_ub,:], '>', vector_ub[(i_ub-1)*N+j_ub])
                    end
                end
            end

            update_model!(model_ub)
            optimize(model_ub)
            W_bound = get_objval(model_ub)

**Comment by odow** [comment] 2019-12-10 14:54
Stay with JuMP+Gurobi.

You can modify JuMP models in-place using:
https://www.juliaopt.org/JuMP.jl/v0.20.0/constraints/#JuMP.set_normalized_coefficient
https://www.juliaopt.org/JuMP.jl/v0.20.0/constraints/#JuMP.set_normalized_rhs

**Comment by zxjroger** [comment] 2019-12-10 18:48
Ok, thank you so much. I will try to see if there is a way to reduce the running time significantly.

**Comment by odow** [comment] 2019-12-10 19:42
You should post a full minimal working example of your code. The snippet you posted above doesn't demonstrate how you are solving the problems in sequence, for example. Do `H_star` and `W` change?

**Comment by zxjroger** [comment] 2019-12-10 19:49
Thanks again, I will do it.

**Comment by zxjroger** [comment] 2019-12-10 20:34
The optimization problem is

max W_{i'j'}
s.t W_{ij} = \lambda^1_i + \lambda^2_j  if H_star[i,j] = 1
     W_{ij} \leq \lambda^1_i + \lambda^2_j  if H_star[i,j] = 0

So the objective is just a scalar W_{i'j'}. All the other W_{ij} such that ij \neq i'j' are constants. H_star is an N by N matrix of constants. Index i and j are both from 1:N, where N could be say 500. W_{i'j'} and lambda are variables. The following code is in a big for loop indexed by i and j. It goes for all the N^2 number of ij combinations. Since N=500 which is big, I want to solve each one as fast as I can.

            model_ub = Model(with_optimizer(Gurobi.Optimizer, Presolve=0, OutputFlag=0))
            @variable(model_ub, W_ub)
            @variable(model_ub, lambda_1[1:N])
            @variable(model_ub, lambda_2[1:N])
            for i_ub = 1:N
                for j_ub = 1:N
                    if i_ub == i && j_ub == j
                        # the constraint for the current ij, or variable W_ub
                        @constraint(model_ub, W_ub <= lambda_1[i_ub] + lambda_2[j_ub])
                    elseif H_star[i_ub,j_ub] == 1
                        # the constraint for ij such that H_star[i,j] = 1
                        @constraint(model_ub, W[i_ub,j_ub] == lambda_1[i_ub] + lambda_2[j_ub])
                    else H_star[i_ub,j_ub] == 0
                        # the constraint for ij such that H_star[i,j] = 0
                        @constraint(model_ub, W[i_ub,j_ub] <= lambda_1[i_ub] + lambda_2[j_ub])
                    end
                end
            end
            @objective(model_ub, Max, W_ub)
            optimize!(model_ub)

To address your question, `W` and `H_star` do not change, and `W_ub` is the objective variable (which is W_{i'j'} in the optimization problem). Right now, it took about 4 seconds on my computer to solve one such problem. I would like to see if it is possible to solve it in milliseconds.

**Comment by odow** [comment] 2019-12-10 20:55
See point 3 here: https://discourse.julialang.org/t/psa-make-it-easier-to-help-you/14757
Also https://stackoverflow.com/help/minimal-reproducible-example
In particular, I don't have data for `N`, `H_star`, or `W`.

> Right now, it took about 4 seconds on my computer to solve one such problem. I would like to see if it is possible to solve it in milliseconds.

Did you look at the Gurobi log (i.e., `OutputFlag = 1`)? Most of the 4 seconds is probably problem set-up. 

Does the time drop when you use `JuMP.direct_mode`?

Why did you set `Presolve=0`? Gurobi can probably efficiently resolve this model.

Is `W` or `H_star` symmetric? You potentially have lots of symmetry you could remove.

> Because I need to solve this problem millions of times, so I am trying to find a way to make it as fast as I can.

Where does the million solves come into this? The first solve might be 4 seconds, but if you are solving small variations, future solves should be on the order of milliseconds (or even less).

Rather than continue posting here, this type of question is more appropriate for our Discourse forum: https://discourse.julialang.org/c/domain/opt/13. It has the added benefit that many more people will read it and may have suggestions.

I would create a full working example that someone can copy-paste into the REPL, run various timings with different settings to see what works and what doesn't, write up what you've found and what you've tried, and then post that in a new post on Discourse.  _Make sure to link back to this issue so that people can read the back-story if they are interested.__

Closing this issue because it is not a bug in Gurobi.jl.

**Closed by odow** 2019-12-10 20:55 UTC
