### ISSUE TITLE
Remove `x ≈ bnd` checks when querying `ConstraintDual` for `SingleVariable` constraints

### ISSUE THREAD

**Issue by mtanneau** [JuliaOpt/Gurobi.jl#250] opened 2019-09-13 23:11 UTC
When querying the dual variable associated to a `MOI.SingleVariable`-in-`S`, the wrapper first check whether the corresponding variable is at its lower/upper bound, e.g.:
```julia
    if x ≈ ub
        return _dual_multiplier(model) * get_dblattrelement(model.inner, "RC", column)
    else
        return 0.0
    end
```
(the offending code is for [`LessThan`](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/MOI_wrapper.jl#L1846) and [`GreaterThan`](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/MOI_wrapper.jl#L1860))

I would argue it is dangerous to do so, and may lead to returning incorrect values. Specifically:
* ~Even if a variable is at its lower/upper bound, it may still be basic (#degeneracy), and thus may have a non-zero reduced cost.~ [edit: I was wrong, this is indeed not a problem]
* More problematic, if the lower/upper bound is zero, then `x ≈ ub` will evaluate to `false` whenever `x` is not _exactly_ zero. This happens all the time when solving with barrier and no crossover, and more generally because of numerical tolerances.
* For `x-in-Interval`, there is no bound check ([here](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/MOI_wrapper.jl#L1881))

**Comment by mlubin** [comment] 2019-09-14 00:34
> Even if a variable is at its lower/upper bound, it may still be basic (#degeneracy), and thus may have a non-zero reduced cost.

Isn't this case handled correctly? Degeneracy would mean that a variable is at its bound and has a *zero* reduced cost. Anyway in this case the code returns `_dual_multiplier(model) * get_dblattrelement(model.inner, "RC", column)`.

> More problematic, if the lower/upper bound is zero, then x ≈ ub will evaluate to false whenever x is not exactly zero.

This is definitely a bug that should be fixed by adding an absolute tolerance.

> For x-in-Interval, there is no bound check (here)

This is intended. What would a bound check do in this case?

**Comment by mtanneau** [comment] 2019-09-14 02:49
> For x-in-Interval, there is no bound check

This was to point out that the wrapper's behaviour is not consistent.
Whether one implements `0 <= x <= 1` with a `GreaterThan(0.0)` + `LessThan(1.0)`, or with a single `Interval(0.0, 1.0)`, the optimization problem is the same.
However, in the former case the wrapper will perform a bound check, but not in the latter. I argue it should not be the case.

> should be fixed by adding an absolute tolerance.

Doing so would only moves the issue.
What if one solves with barrier and a relaxed optimality tolerance (for instance to stabilize a cutting plane or column generation algorithm)? This yields an interior point `x`, and it may well be the case that, say, bound constraints are not tight, but the corresponding reduced costs are still non-zero (because the barrier stopped early). It means the user would _also_ have to take care of the tolerances when querying the reduced costs.
What if simplex tolerances are relaxed? Would one have to adjust the tolerances in the MOI wrapper too?

Finally, this part of the code is not even needed for correctness. All it does is enforce a convention (complementary slackness), which is already enforced by Gurobi. Assuming there are no numerical edge cases (like the zero bound), there is no difference between checking or not checking.
And it cannot be about performance, since looking-up the reduced cost is super fast, and the check introduces an additional query to get the bound value.

**Comment by mlubin** [comment] 2019-09-14 17:07
As you mention, if a variable has lower and upper bounds, there are two dual multipliers that could in principle be non-zero at the same time. MOI was designed with this in mind and allows solvers to return two duals if specify the problem with two constraints (`SingleVariable`-in-`LessThan` and `SingleVariable`-in-`GreaterThan`). If you specify the constraint as (`SingleVariable`-in-`Interval`) then we have no choice but to return a single dual which is equivalent to a reduced cost.

No matter which convergence tolerances you use, Gurobi doesn't provide a way to access separate duals on the lower and upper bounds, so we have to guess whether the reduced cost is really the dual on the lower bound or the dual on the upper bound. If we removed the `x ≈ ub` check completely, we would return the same dual for the lower and upper bounds regardless of which bound was actually active, which is plain incorrect.

There are definitely possible improvements to be in the heuristic to "guess whether the reduced cost is really the dual on the lower bound or the dual on the upper bound", but removing the check altogether is incorrect.

**Comment by mtanneau** [comment] 2019-09-14 18:46
Right, I forgot that the bounds can be given by two different constraints.

**Comment by blegat** [comment] 2019-09-15 14:16
Then maybe we should check whether `x` is closer to the lower or upper bound. And only return a nonzero dual for the bound for which it is closer.

**Comment by mtanneau** [comment] 2019-09-17 02:15
Simple case: there is only one `MOI.SingleVariable`-in-`S`. Then the corresponding dual is simply the reduced cost of `x` (as is done for `Interval` and `EqualTo`).

Annoying case: there are both a `LessThan` (`x <= u`) and a `GreaterThan` (`l <= x`) constraint. In that case, Gurobi returns only one value, and the wrapper needs to figure out whether it corresponds to the upper bound or lower bound constraint. Am I correct so far?

[ I'm picking the math & notation from the [Mosek help](https://docs.mosek.com/9.0/capi/prob-def-linear.html).]
In the latter case, the bounds write `l <= x <= u`, and there are two corresponding duals `s_l >= 0` and `s_u <= 0`.
MOI allows to query `s_l` and `s_u` separately, while Gurobi only gives access (through the reduced cost) to `s_l + s_u`.

Given `s_l + s_u`, one way to recover `s_l` and `s_u` is to look at the primal value of `x`: whichever bound constraint is not active will have a dual of zero. That's the current approach. There's actually another case when that will fail: when the two bounds are the same.
```julia
import MathOptInterface
MOI = MathOptInterface
import Gurobi

grb = Gurobi.Optimizer()

# Create the following problem:
# min x
# s.t. 1 <= x <= 1
x = MOI.add_variable(grb)
xl = MOI.add_constraint(grb, MOI.SingleVariable(x), MOI.GreaterThan(1.0))
xu = MOI.add_constraint(grb, MOI.SingleVariable(x), MOI.LessThan(1.0))
MOI.set(grb, MOI.ObjectiveSense(), MOI.MIN_SENSE)
fobj = MOI.ScalarAffineFunction([MOI.ScalarAffineTerm(1.0, x)], 0.0)
MOI.set(grb, MOI.ObjectiveFunction{typeof(fobj)}(), fobj)

MOI.optimize!(grb)

# Query the duals
sl = MOI.get(grb, MOI.ConstraintDual(), xl)  # returns 1.0
su = MOI.get(grb, MOI.ConstraintDual(), xu)  # /!\ also returns 1.0
```
Here, both tests `x ≈ bnd` evaluate to `true`, and both duals are the same (whereas `su` should be non-positive).
FYI, running the same code with Mosek yields `sl = 1.0` and `su = 0.0`. With Tulip I got `sl = 2` and `su = -1` (though I wouldn't vouch for Tulip's correctness).


**How about looking at the sign of the reduced cost instead?**
If the lower bound is active, the reduced cost will be non-negative. If the upper bound is active, the reduced cost will be non-positive.
Therefore, rather than checking the primal bound, we could just check the sign of the reduced cost, and return zero if not of the correct sign.

**Comment by odow** [comment] 2019-09-17 02:24
Nice! The sign is actually a good way to do this.

**Comment by odow** [comment] 2019-09-17 03:09
I've updated #252 with an implementation that checks the sign.

**Comment by mlubin** [comment] 2019-09-17 12:07
The nice property of deciding based on the sign is that the answer can be wrong by at most the dual feasibility tolerance (`OptimalityTol` in Gurobi). This is an improvement worth implementing, but it's still not perfect.

**Comment by mtanneau** [comment] 2019-09-17 15:13
FYI, I opened a ticket with Gurobi. Maybe they'll decide to implement that feature...

**Closed** 2019-09-22 23:10 UTC
Labels: Wrapper: MathOptInterface

**Comment by ktnr** [comment] 2020-03-02 10:05
Please correct me if I'm wrong, I have never worked with JuliaOpt and do not know the use case for `SingleVariable`.

Given your example problem

min x
s.t. 
x >= l
-x >= -u
x >= 0

the corresponding dual is

max l * sl - u * su
s.t.
sl - su <= 1
sl, su >= 0

The reduced cost of x is 1 - sl + su.

For problems involving more variables and constraints, and therefore more terms in the reduced costs expression of x, the sign of the reduced costs of x cannot necessarily give you information on which bound on x is active.

Am I missing something?

**Comment by odow** [comment] 2020-03-02 14:37
We have the convention that variables can only have one bound, so we cannot have `x >= l` and `x >= 0`. 

In addition, we do not use LP duality. See 
- https://www.juliaopt.org/JuMP.jl/stable/constraints/#constraint_duality-1
- https://www.juliaopt.org/MathOptInterface.jl/stable/apimanual/#Duals-1.
