### ISSUE TITLE
julia0.6 add error

### ISSUE THREAD

**Issue by WANGrfy** [JuliaOpt/Gurobi.jl#229] opened 2019-08-08 02:59 UTC
julia> Pkg.add("LinearAlgebra")
ERROR: unknown package LinearAlgebra

please help me solve the problem！
Thanks

**Comment by blegat** [comment] 2019-08-08 06:23
Duplicate of https://github.com/JuliaOpt/Gurobi.jl/issues/229

**Closed by blegat** 2019-08-08 06:23 UTC
